// This file is generated by generate_ast.rs
use crate::lexer::{Token};
use crate::parser::{Expr};

pub trait StmtVisitor<R> {
    fn visit_expression_stmt(&mut self, expr: &Stmt) -> R;
    fn visit_print_stmt(&mut self, expr: &Stmt) -> R;
    fn visit_var_stmt(&mut self, expr: &Stmt) -> R;
}

pub enum Stmt {
    Expression {
        expression: Box<Expr>,
    },
    Print {
        expression: Box<Expr>,
    },
    Var {
        name: Token,
        initializer: Option<Box<Expr>>,
    },
}

impl Stmt {
    pub fn accept<R>(&self, visitor: &mut dyn StmtVisitor<R>) -> R {
        match self {
            Stmt::Expression { .. } => visitor.visit_expression_stmt(self),
            Stmt::Print { .. } => visitor.visit_print_stmt(self),
            Stmt::Var { .. } => visitor.visit_var_stmt(self),
        }
    }
}
